# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

lane :build do
  sync_certificates()
  increment_build_number()
  # Compile the app and save the build at the folder "Builds/"
  gym()
end

lane :beta do
  build()
  # Upload the build to Testflight
  pilot()
end

lane :sync_certificates do
  # Download the certificates/profiles
  match(readonly: true, type: "appstore")
end
