# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

keychain_name = 'fastlane_tmp_keychain'
 
lane :sync_certificates do
match(
  git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"],
  readonly: is_ci,
  type: "appstore",
  keychain_name: keychain_name
  )
end

desc "Create ipa"
lane :build do
  #setup_ci
  #update profiles
  sync_certificates
  # Increases the build number by 1
  increment_build_number
  # Creates a signed file
  gym
end



